
version: '3.9'

services:
    jupyter:
        environment:
            JUPYTER_TOKEN: "docker"
        build: .
        #image: local_stable_diffusion_v2
        image: pytorch_stable_diffusion_v2
        command: nvidia-smi
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        ports:
            - 8888:8888
        volumes:
            - ./project:/project
        command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]